services:
  mongo:
    image: "mongo:6.0.21"
    container_name: mongodb_01
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpass
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres_django
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo-express:
    container_name: mongo_Express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  redis:
    image: "redis:alpine"
    container_name: redis_01
    restart: always

  django:
    build: ./Backend
    container_name: django_app
    restart: always
    depends_on:
      - redis
      - db
      - mongo
    env_file:
      - .env
    command: >
      sh -c 'python manage.py migrate &&
      gunicorn --chdir Backend --bind 0.0.0.0:8000 wsgi:application'
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  celery:
    build:
      context: ./Backend
    container_name: celery_worker_01
    restart: always
    depends_on:
      - redis
      - django
    command: >
        sh -c 'celery -A Backend.celery_app worker --loglevel=info'
    env_file:
      - .env
    volumes:
      - .:/app

  flower:
    image: mher/flower
    container_name: celery_Flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # or host.docker.internal:6380/0 depending on setup
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    depends_on:
      - celery
      - redis
      - django

volumes:
  mongodb_data:
  postgres_data: