# Generated by Django 5.1.7 on 2025-04-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_homework_deadline_homework_week_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='note',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='test',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='video',
            name='week_number',
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='course.course')),
            ],
            options={
                'unique_together': {('course', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='course.week'),
        ),
        migrations.AddField(
            model_name='note',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='course.week'),
        ),
        migrations.AddField(
            model_name='test',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='course.week'),
        ),
        migrations.AddField(
            model_name='video',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.week'),
        ),
    ]
