# Generated by Django 5.1.7 on 2025-04-25 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_homework_week_number_remove_note_week_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['week_number']},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Optional: link to the video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='week',
            field=models.ForeignKey(blank=True, help_text='(temporarily nullable so migrations run cleanly)', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.week'),
        ),
        migrations.AlterField(
            model_name='note',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Make nullable temporarily for migrations', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.week'),
        ),
        migrations.AlterField(
            model_name='test',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Temporarily nullable for migrations', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.week'),
        ),
        migrations.AlterField(
            model_name='video',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Temporarily nullable for migrations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.week'),
        ),
    ]
