# Generated by Django 5.1.7 on 2025-04-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_week_options_remove_homework_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='notes/%Y/%m/%d/'),
        ),
    ]
