# Generated by Django 5.1.7 on 2025-04-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_note_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='File',
            new_name='file',
        ),
    ]
