# Generated by Django 5.1.7 on 2025-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_video_url_video_file_alter_video_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/%Y/%m/%d/'),
        ),
    ]
