# Generated by Django 5.1.7 on 2025-04-25 09:40

import user.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user.manager.CustomUserManager()),
            ],
        ),
    ]
